language: java
sudo: required
services:
  - docker

before_install:
  - docker build -t hareeshravi01/redesigned-octo-umbrella .

script:
  - docker run -e CI=true hareeshravi01/redesigned-octo-umbrella npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-856551873424"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
