
#FROM openjdk:8-jre-alpine

FROM maven:3.6.3-openjdk-8-slim

WORKDIR /app

COPY pom.xml .

RUN mvn -e -B dependency:resolve

COPY src ./src

RUN mvn -e -B package

CMD ["java", "-jar", "/app/target/dockertest-0.0.1-SNAPSHOT.jar"]
