
FROM maven:3.6.3-openjdk-8-slim
# RUN addgroup --system spring && adduser --system --ingroup spring spring
# USER spring:spring
COPY ./pom.xml .
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
CMD ["mvn", "-e", "-B", "test"]
